site_name: gp_active_mcmc
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: true
            show_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_source: false
            heading_level: 2


nav:
  - Home: index.md
  - User Guide:
      - Quickstart: guide/quickstart.md
      - Examples: guide/examples.md
  - API Reference:
      - Inference: api/inference.md
      - Surrogates: api/surrogates.md
      - Diagnostics: api/diagnostics.md
      - Utils: api/utils.md
